version: '3.8'

services:
  app:
    build:
      context: .
    container_name: app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db/measurement-db
      SERVER_PORT: 8080
    ports:
      - 8080:8080

  db:
    image: postgres:latest
    container_name: db
    environment:
      POSTGRES_USER: etimoshin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: measurement-db
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@admin.com
        PGADMIN_DEFAULT_PASSWORD: root
    ports:
       - 5050:80